// top level objects
module.exports.ARRANGEMENT_TYPE = 'arrangement';
module.exports.HANGOVER_TYPE = 'hangover';
module.exports.SEMESTER_TYPE = 'semester';
module.exports.ALBUM_TYPE = 'album';
module.exports.CONCERT_TYPE = 'concert';
module.exports.GENRE_TYPE = 'genre';
module.exports.ARTIST_TYPE = 'artist';
module.exports.TAG_TYPE = 'tag';
// essentially enums
module.exports.ARRANGEMENT_TYPE_TYPE = 'arrangement_type';
module.exports.ALBUM_FORMAT_TYPE = 'album_format';
module.exports.CONCERT_TYPE_TYPE = 'concert_type';
module.exports.KEY_TYPE = 'key';
// relationships
module.exports.ALBUM_SEMESTER_RELATIONSHIP_TYPE = 'album_semester_relationship';
module.exports.ARRANGEMENT_ALBUMS_RELATIONSHIP_TYPE = 'arrangement_albums_relationship';
module.exports.ARRANGEMENT_ARRANGERS_RELATIONSHIP_TYPE = 'arrangement_arrangers_relationship';
module.exports.ARRANGEMENT_ARTIST_RELATIONSHIP_TYPE = 'arrangement_artist_relationship';
module.exports.ARRANGEMENT_CONCERTS_RELATIONSHIP_TYPE = 'arrangement_concerts_relationship';
module.exports.ARRANGEMENT_GENRE_RELATIONSHIP_TYPE = 'arrangement_genre_relationship';
module.exports.ARRANGEMENT_SEMESTER_ARRANGED_RELATIONSHIP_TYPE = 'arrangement_semester_arranged_relationship';
module.exports.ARRANGEMENT_SEMESTERS_PERFORMED_RELATIONSHIP_TYPE = 'arrangement_semesters_performed_relationship';
module.exports.ARRANGEMENT_SOLOISTS_RELATIONSHIP_TYPE = 'arrangement_soloists_relationship';
module.exports.ARRANGEMENT_TAG_RELATIONSHIP_TYPE = 'arrangement_tag_relationship';
module.exports.BM_SEMESTER_RELATIONSHIP_TYPE = 'bm_semester_relationship';
module.exports.CONCERT_SEMESTER_RELATIONSHIP_TYPE = 'concert_semester_relationship';
module.exports.HANGOVER_GRADUATION_SEMESTER_RELATIONSHIP_TYPE = 'hangover_graduation_semester_relationship';
module.exports.MD_CONCERT_RELATIONSHIP_TYPE = 'md_concert_relationship';
module.exports.MD_SEMESTER_RELATIONSHIP_TYPE = 'md_semester_relationship';
module.exports.PRESIDENT_SEMESTER_RELATIONSHIP_TYPE = 'president_semester_relationship';
